// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ols_rcpp
List ols_rcpp(NumericVector y, int p, int q);
RcppExport SEXP _robarma_ols_rcpp(SEXP ySEXP, SEXP pSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(ols_rcpp(y, p, q));
    return rcpp_result_gen;
END_RCPP
}
// mle_rcpp
List mle_rcpp(NumericVector y, int p, int q);
RcppExport SEXP _robarma_mle_rcpp(SEXP ySEXP, SEXP pSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(mle_rcpp(y, p, q));
    return rcpp_result_gen;
END_RCPP
}
// ftau_rcpp
List ftau_rcpp(NumericVector y, int p, int q);
RcppExport SEXP _robarma_ftau_rcpp(SEXP ySEXP, SEXP pSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(ftau_rcpp(y, p, q));
    return rcpp_result_gen;
END_RCPP
}
// s_rcpp
List s_rcpp(NumericVector y, int p, int q);
RcppExport SEXP _robarma_s_rcpp(SEXP ySEXP, SEXP pSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(s_rcpp(y, p, q));
    return rcpp_result_gen;
END_RCPP
}
// mm_rcpp
List mm_rcpp(NumericVector y, int p, int q);
RcppExport SEXP _robarma_mm_rcpp(SEXP ySEXP, SEXP pSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(mm_rcpp(y, p, q));
    return rcpp_result_gen;
END_RCPP
}
// bip_mm_rcpp
List bip_mm_rcpp(NumericVector y, int p, int q);
RcppExport SEXP _robarma_bip_mm_rcpp(SEXP ySEXP, SEXP pSEXP, SEXP qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    rcpp_result_gen = Rcpp::wrap(bip_mm_rcpp(y, p, q));
    return rcpp_result_gen;
END_RCPP
}
// simulate_rcpp
NumericVector simulate_rcpp(NumericVector phi, NumericVector theta, double mu, int n, int burn_in, int seed);
RcppExport SEXP _robarma_simulate_rcpp(SEXP phiSEXP, SEXP thetaSEXP, SEXP muSEXP, SEXP nSEXP, SEXP burn_inSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type burn_in(burn_inSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_rcpp(phi, theta, mu, n, burn_in, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_robarma_ols_rcpp", (DL_FUNC) &_robarma_ols_rcpp, 3},
    {"_robarma_mle_rcpp", (DL_FUNC) &_robarma_mle_rcpp, 3},
    {"_robarma_ftau_rcpp", (DL_FUNC) &_robarma_ftau_rcpp, 3},
    {"_robarma_s_rcpp", (DL_FUNC) &_robarma_s_rcpp, 3},
    {"_robarma_mm_rcpp", (DL_FUNC) &_robarma_mm_rcpp, 3},
    {"_robarma_bip_mm_rcpp", (DL_FUNC) &_robarma_bip_mm_rcpp, 3},
    {"_robarma_simulate_rcpp", (DL_FUNC) &_robarma_simulate_rcpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_robarma(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
