# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ols_rcpp <- function(y, p, q) {
    .Call(`_robarma_ols_rcpp`, y, p, q)
}

mle_rcpp <- function(y, p, q) {
    .Call(`_robarma_mle_rcpp`, y, p, q)
}

ftau_rcpp <- function(y, p, q) {
    .Call(`_robarma_ftau_rcpp`, y, p, q)
}

s_rcpp <- function(y, p, q) {
    .Call(`_robarma_s_rcpp`, y, p, q)
}

mm_rcpp <- function(y, p, q) {
    .Call(`_robarma_mm_rcpp`, y, p, q)
}

bip_mm_rcpp <- function(y, p, q) {
    .Call(`_robarma_bip_mm_rcpp`, y, p, q)
}

simulate_rcpp <- function(phi, theta, mu, n, burn_in = 100L, seed = 0L) {
    .Call(`_robarma_simulate_rcpp`, phi, theta, mu, n, burn_in, seed)
}

